language: julia

os:
  - linux

julia:
  - 0.6
  - nightly

after_success:
  - julia -e 'cd(Pkg.dir("LinearAlgebra")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
