language: julia

os:
  - linux

julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
  - julia: nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())';
