# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Linux
  
  pool:
    vmImage: 'Ubuntu 16.04'

  strategy:
    matrix:
      Julia 1.0:
        JULIA_VERSION: '1.0.1'

  steps:
  - script: |
      wget -nv https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-$(JULIA_VERSION)-linux-x86_64.tar.gz
      tar zxf julia-$(JULIA_VERSION)-linux-x86_64.tar.gz
    displayName: 'Download and extract Julia 1.0'

  - script: |
      ./julia-$(JULIA_VERSION)/bin/julia --project=@. -e 'using Pkg; Pkg.instantiate()'
      ./julia-$(JULIA_VERSION)/bin/julia --project=@. -e 'using Pkg; Pkg.test("GenericLinearAlgebra")'
    displayName: 'Run the tests'
